ChatGPT/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("tourplan.urls")),
]

tourplan/urls.py
from django.urls import path

from . import views

app_name = "tourplan"
urlpatterns = [
    path("", views.search, name="search"),
]

tourplan/models.py
from django.db import models

# Create your models here.

tourplan/views.py
from django.shortcuts import render, redirect
import openai
import os
# Create your views here.
from django.http import HttpResponse

openai.api_key = os.environ["GPTPATH"]
def search(request):
    if request.POST:
        place = request.POST["pref_id"]
        period = request.POST["day"]
        trans = request.POST["trans"]
        get_date = request.POST["date"].split("-")
        date = get_date[0] + "年" + get_date[1] + "月" + get_date[2] + "日"
        interests = request.POST.getlist("interests")
        keywords = request.POST["key"]
        text = f"""
        以下の条件に合わせた旅行プランを考え，先ほど示した命令書に100%必ず従え。余計な文章は必ず省け。
        日程：{date}
        日数：{period}
        交通手段:{trans}
        場所：{place}
        ジャンル:{" ".join(interests)}
        キーワード:{keywords}
        """

        rule = """
        #命令書:
        あなたはプロの旅行ガイドです。
        以下の制約と条件をもとに，最高の旅行プランを提案してください。

        #制約条件:
        ・日程：
            日程はあくまでも季節を考慮するためのものである。
        ・日数：
            日帰りや1泊2日など指定された条件で考える必要がある。1泊2日であれば1日目と2日目を考える。2泊3日であれば1日目, 2日目, 3日目を考える。
        ・交通手段:
            指定された交通手段で旅行プランを考える。
        ・場所：
            指定された場所の旅行プランを考える。
        ・ジャンル:
            指定されたジャンルを含めた旅行プランを考える。指定されなければ特に考えなくて良い。
        ・キーワード:
            指定されたキーワードを含めた旅行プランを考える。指定されなければ特に考えなくて良い。

        #出力フォーマット: 
            1日目\n
            00:00 : 場所-説明\n
            滞在時間 : n分\n
            移動:交通手段-n分\n
            00:00 : 場所-説明\n
            滞在時間 : n分\n
            ...
            移動:交通手段-n分\n
            00:00 : 場所-説明\n
            滞在時間 : n分\n
            
            2日目\n
            00:00 : 場所-説明\n
            滞在時間 : n分\n
            移動:交通手段-n分\n
            00:00 : 場所-説明\n
            滞在時間 : n分\n
            ...
            移動:交通手段-n分\n
            00:00 : 場所-説明\n
            滞在時間 : n分\n
        
        #注意
        ・日数が日帰りと指定された場合は出力フォーマットの"1日目"のところを"日帰り"にかえろ。
        ・日数が1泊2日の場合は1日目と2日目，2泊3日の場合は1日目と2日目と3日目を考えろ。その他も同様。
        ・一度行った場所はなるだけ他の日で行かないようにしてください。再訪は禁止。
        """
        
        messages_pre = []
        messages_pre.append({"role": "system", "content": rule})
        messages_pre.append({"role": "user", "content": text})
        response_pre = openai.ChatCompletion.create(
            model="gpt-3.5-turbo",
            messages=messages_pre,
        )
        results = response_pre["choices"][0]["message"]["content"]
        context = {
            "results" : results.split("\n")
        }
        print(results)
        # return render(request, "tourplan/results.html", context)
        return render(request, "tourplan/results.html", context)


    return render(request, "tourplan/index.html")

tourplan/templates/base.html
{% load static %}
<!doctype html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}{% endblock %}
    </title>
    <link rel="stylesheet" type="text/css" href="{% static 'tourplan/base.css' %}">
  </head>
  <body>
    <header>
        <h1>ChatGPTによる旅行プランシステム</h1>
    </header>
    <nav>
      <ul>
          <li><a href="#">ホーム</a></li>
          <li><a href="{% url 'tourplan:search' %}">プラン検索</a></li>
          <li><a href="#">お問い合わせ</a></li>
      </ul>
    </nav>
    {% block content %}{% endblock %}
    <footer>
      <p>&copy; 2023 旅行プランシステム. All rights reserved.</p>
    </footer> 
  </body>
</html>

tourplan/templates/tourplan/index.html
{% extends "base.html" %}

{% block title %}旅行プラン検索{% endblock %}
{% block content%}

<main>
    <form class="search-form" method="POST">{% csrf_token %}
        <div class="form-group">
            <label for="prefecture">都道府県:</label>
            <select name="pref_id" required>
                <option value="" selected></option>
                <option value="北海道">北海道</option>
                <option value="青森県">青森県</option>
                <option value="岩手県">岩手県</option>
                <option value="宮城県">宮城県</option>
                <option value="秋田県">秋田県</option>
                <option value="山形県">山形県</option>
                <option value="福島県">福島県</option>
                <option value="茨城県">茨城県</option>
                <option value="栃木県">栃木県</option>
                <option value="群馬県">群馬県</option>
                <option value="埼玉県">埼玉県</option>
                <option value="千葉県">千葉県</option>
                <option value="東京都">東京都</option>
                <option value="神奈川県">神奈川県</option>
                <option value="新潟県">新潟県</option>
                <option value="富山県">富山県</option>
                <option value="石川県">石川県</option>
                <option value="福井県">福井県</option>
                <option value="山梨県">山梨県</option>
                <option value="長野県">長野県</option>
                <option value="岐阜県">岐阜県</option>
                <option value="静岡県">静岡県</option>
                <option value="愛知県">愛知県</option>
                <option value="三重県">三重県</option>
                <option value="滋賀県">滋賀県</option>
                <option value="京都府">京都府</option>
                <option value="大阪府">大阪府</option>
                <option value="兵庫県">兵庫県</option>
                <option value="奈良県">奈良県</option>
                <option value="和歌山県">和歌山県</option>
                <option value="鳥取県">鳥取県</option>
                <option value="島根県">島根県</option>
                <option value="岡山県">岡山県</option>
                <option value="広島県">広島県</option>
                <option value="山口県">山口県</option>
                <option value="徳島県">徳島県</option>
                <option value="香川県">香川県</option>
                <option value="愛媛県">愛媛県</option>
                <option value="高知県">高知県</option>
                <option value="福岡県">福岡県</option>
                <option value="佐賀県">佐賀県</option>
                <option value="長崎県">長崎県</option>
                <option value="熊本県">熊本県</option>
                <option value="大分県">大分県</option>
                <option value="宮崎県">宮崎県</option>
                <option value="鹿児島県">鹿児島県</option>
                <option value="沖縄県">沖縄県</option>
            </select>
        </div>

        <div class="form-group">
            <label for="date">日程:</label>
            <input type="date" id="date" name="date" required>
        </div>

        <div class="form-group" id="night-days">
            <p><label for="duration">日数:</label>
                <select name="day" required>
                    <option value=""></option>
                    <option value="日帰り">日帰り</option>
                    <option value="1泊2日">1泊2日</option>
                    <option value="2泊3日">2泊3日</option>
                    <option value="3泊4日">3泊4日</option>
                    <option value="4泊5日">4泊5日</option>
                </select>
            </p>
        </div>

        <div class="form-group">
            <label for="transport">移動手段:</label>
            <select id="transport" name="trans" required>
                <option value="">移動手段を選択してください</option>
                <option value="電車">電車</option>
                <option value="車">車</option>
                <option value="バス">バス</option>
                <!-- 他の移動手段のオプションを追加 -->
            </select>
        </div>
        <div class="form-group">
            <label for="keywords">キーワード:</label>
            <div class="keywords">
                <input type="text" name="key" placeholder="例) 金閣寺　銀閣寺">
            </div>
        </div>
        <div class="form-group">
            <label for="interests">観光スポット:</label>
            <div id="interests">
                <input type="checkbox" id="nature" value="自然" name="interests">
                <label for="nature">自然</label>
                <input type="checkbox" id="amusement-park" value="遊園地" name="interests">
                <label for="amusement-park">遊園地</label>
                <input type="checkbox" id="temple" value="神社・寺" name="interests">
                <label for="amusement-park">神社・寺</label>
                <input type="checkbox" id="sea" value="海" name="interests">
                <label for="amusement-park">海</label>
                <input type="checkbox" id="museum" value="美術館・博物館" name="interests">
                <label for="amusement-park">美術館・博物館</label>
                <input type="checkbox" id="aquarium" value="水族館" name="interests">
                <label for="amusement-park">水族館</label>
                <input type="checkbox" id="eating" value="食べ歩き" name="interests">
                <label for="amusement-park">食べ歩き</label>
                <input type="checkbox" id="glamping" value="グランピング" name="interests">
                <label for="amusement-park">グランピング</label>
                <input type="checkbox" id="camp" value="キャンプ" name="interests">
                <label for="amusement-park">キャンプ</label>
                <!-- 他の観光スポットのチェックボックスを追加 -->
            </div>
        </div>

        <button type="submit" class="btn">旅行プランを検索する</button>
    </form>
</main>
{% endblock %}

tourplan/templates/tourplan/results.html
{% extends "base.html" %}
{% load tags %}

{% block title %}旅行プラン検索{% endblock %}
{% block content%}

<div>
{% for result in results %}
    {% if result|last_two == '日目' or result == '日帰り' %}
        </div>      
        <div class="plan">
            <h2>{{ result }}</h2>
    {% elif result|first_two == '移動' %}
            <p>　・</p>
            <p>　・</p>
            <p>　・</p>
            <p>{{result|trans_min}}</p>
    {% elif result|time %}
            <p>　・</p>
            <p>　・</p>
            <p>　・</p>
            <p>{{ result }}</p> 
    {% endif %}
{% endfor %}
</div>


{% endblock %}